// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_sbar_TMBExports
#include <TMB.hpp>
#include "csa.hpp"
#include "schnute_new_V2.hpp"
#include "schnute_orig.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "csa") {
    return csa(this);
  } else if(model == "schnute_new_V2") {
    return schnute_new_V2(this);
  } else if(model == "schnute_orig") {
    return schnute_orig(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
