---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# sbar - Stage-based assessments in R 

<!-- badges: start -->
<!-- badges: end -->

**sbar** is a package that provides functions to allow the user to run various stage-based fisheries assessments in R. The stage-based assesments available are versions of the current (2020) Catch-Survey Analysis (CSA) found in the the NOAA Fish and Fisheries Toolbox and an implementation of a size-based delay-difference model described in the theoretical paper by Schnute (1987). Model theory, implementation and testing are detailed in a manuscript currently under review.

## Installation
This package involves C++ code and the modelling framework of the package `TMB`.  Please ensure that you are able to compile source code and that this package is running smoothly on your device. Package has not been tested on the most recent version of R (>=4.0) as of yet 

And sbar package can be installed from Github with:

``` r
# install.packages("devtools")
devtools::install_github("lbatts/sbar")
```
## Examples

To learn more about sbar assessments and to see examples 
``` r
browseVignettes("sbar")
```
